### ISSUE TITLE
Likes Calculation error on the comments

### ISSUE THREAD

**Issue by rockydude** [Darrenmeehan/BuddyPress-Like#10]
Hello

I have this plugin installed on my site and i am having problem. There is a problem with the way it calculates the likes for the comments.

This is what i did
1)post an activity and like it.
2)comment on that activity and like the comment
3)Unlike the like on the activity. (not on the comment)

When i do this, since i removed the like for the activity, the comment likes get messed up. it shows "-2 likes" on the comments.

can you tell me how to fix this calculation error?
thanks

**Comment by Darrenmeehan** [comment]
This has been fixed a few versions ago. Thanks for highlighting.
