### ISSUE TITLE
JS conflicts with All Wordpress JS and Jquery System

### ISSUE THREAD

**Issue by fffiloni** [Darrenmeehan/BuddyPress-Like#11]
Hi !

Buddypress Like blocks all the JQuery et JS moves in wordpress 3.9 and buddypress 2.0

Did you noticed that ? 

So the plugin works, but when you want to modify the widgets (for example), it's impossible. 
The hover on menu in wordpress' back office doesn't works also... 

-> the auto-suggest in private message doesn't work neither...

And then there are conflicts with BP Activity Privacy, and many many plugins ! 

Haha, not bad, but maybe we could try to fix it together ? 

Cheers !

**Comment by phylaxis** [comment]
I just installed the latest version and I'm seeing this error. Any ideas why? In can eat helps this is the specific JS error I'me seeing:

`TypeError: jq('.like, .unlike').live is not a function. (In 'jq('.like, .unlike').live', 'jq('.like, .unlike').live' is undefined)`
