### ISSUE TITLE
plugin does not work with WordPress 4.3.1  or 4.2.5 

### ISSUE THREAD

**Issue by egarim** [Darrenmeehan/BuddyPress-Like#27]
Hi, I want to use your plugin, it install ok on  WordPress 4.3.1  and  4.2.5  but when you activate the plugin it goes into a blank screen and you are not able  to open the wordpress site again

**Comment by nineyards** [comment]
Im using WP 4.4 and the plugin works fine

**Comment by Darrenmeehan** [comment]
Thanks egarim for the feedback, what version was it you were using? These has been no reports of any issues with 0.3. 

Thanks nineyards, glad to working well for you.
