### ISSUE TITLE
Like/Unlike with Custom Message

### ISSUE THREAD

**Issue by Grendel61** [Darrenmeehan/BuddyPress-Like#29]
I set a custom message - Stand Up! versus Like. 

On the Activities. 

The Like shows on a refreshed screen Stand Up! with the thumb as the default. When I click the button, it shows, "UNLIKE". If I click it again its says, "LIKE". If I refresh then it shows the expected message.

**Comment by Darrenmeehan** [comment]
This is now fixed. Thanks again!
