### ISSUE TITLE
Issues with liking replies

### ISSUE THREAD

**Issue by colabsadmin** [Darrenmeehan/BuddyPress-Like#8]
Found a few issues when liking replies

1 - The actual activity of liking the reply is not picking up the reply authors name.  

"Joe liked 's activity 42 seconds ago"

Notice the " 's " without the name.

2 - I'm getting strange errors that I havent dug into for possible causes, but happens on liked replies

Warning: array_keys() expects parameter 1 to be array, boolean given in plugins/buddypress-like/includes/like-functions.php on line 458
, and -2 liked this.

**Comment by Darrenmeehan** [comment]
This has been fixed, closing as old issue. Thanks for the feedback by the way, you've provided quite a lot of help which I appreciate.
