### ISSUE TITLE
Extra query

### ISSUE THREAD

**Issue by mpa4hu** [Darrenmeehan/BuddyPress-Like#9]
I wrote on wordpress suppor forum, but Ill write it here too

<blockquote>//TODO: I believe there is a bp core function for this.
</blockquote>
since `bplike_activity_button` runs inside loop, there is no need to add extra query.

you can use functions like `bp_get_activity_type()` as you are using `bp_get_activity_id()`

**Comment by Darrenmeehan** [comment]
Started using these functions a few versions ago. Marking as fixed. Thanks!
